"""Add user_reports table

Revision ID: f562a3476362
Revises: 82bb8e0a0bee
Create Date: 2026-05-08 01:38:18.592481
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f562a3476362'
down_revision: Union[str, None] = '82bb8e0a0bee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('reported_user_id', sa.UUID(), nullable=True),
    sa.Column('reported_activity_id', sa.UUID(), nullable=True),
    sa.Column('reported_group_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reported_activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['reported_group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['reported_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('activities', 'lat',
               existing_type=sa.NUMERIC(precision=10, scale=7),
               type_=sa.Float(precision=10),
               existing_nullable=True)
    op.alter_column('activities', 'lng',
               existing_type=sa.NUMERIC(precision=10, scale=7),
               type_=sa.Float(precision=10),
               existing_nullable=True)
    op.alter_column('activities', 'city',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Bangalore'::character varying"))
    op.alter_column('activities', 'scheduled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('activities', 'confirmed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('activities', 'duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('180'))
    op.alter_column('activities', 'group_size_min',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('4'))
    op.alter_column('activities', 'group_size_max',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('8'))
    op.alter_column('activities', 'women_only',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('activities', 'max_groups',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('3'))
    op.alter_column('activities', 'phone_free_encouraged',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('activities', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'open'::character varying"))
    op.alter_column('activities', 'is_local_event',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('activities', 'min_capacity',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('4'))
    op.alter_column('activities', 'max_capacity',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('50'))
    op.alter_column('activities', 'ticket_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'free'::character varying"))
    op.alter_column('activities', 'ticket_price_inr',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('activities', 'visibility',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'public'::character varying"))
    op.alter_column('activities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_activities_area'), table_name='activities')
    op.drop_index(op.f('idx_activities_category'), table_name='activities')
    op.drop_index(op.f('idx_activities_city'), table_name='activities')
    op.drop_index(op.f('idx_activities_is_local_event'), table_name='activities')
    op.drop_index(op.f('idx_activities_scheduled_at'), table_name='activities')
    op.drop_index(op.f('idx_activities_status'), table_name='activities')
    op.drop_index(op.f('idx_activities_tags'), table_name='activities', postgresql_using='gin')
    op.alter_column('admin_notifications', 'delivered_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('admin_notifications', 'opened_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('admin_notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_messages', 'message_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'text'::character varying"))
    op.alter_column('chat_messages', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_chat_messages_expires'), table_name='chat_messages')
    op.drop_index(op.f('idx_chat_messages_group'), table_name='chat_messages')
    op.alter_column('flagged_users', 'flag_type',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'manual'::character varying"))
    op.alter_column('flagged_users', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('flagged_users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_flagged_users_status'), table_name='flagged_users')
    op.alter_column('friend_connections', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('friend_connections', 'compatibility_score',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Float(precision=5),
               existing_nullable=True)
    op.alter_column('friend_connections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('friend_connections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_friend_conn_friend'), table_name='friend_connections')
    op.drop_index(op.f('idx_friend_conn_user'), table_name='friend_connections')
    op.alter_column('group_members', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'member'::character varying"))
    op.alter_column('group_members', 'checked_in',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('group_members', 'sos_triggered',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('group_members', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_group_members_group'), table_name='group_members')
    op.drop_index(op.f('idx_group_members_user'), table_name='group_members')
    op.alter_column('groups', 'match_score',
               existing_type=sa.NUMERIC(precision=5, scale=3),
               type_=sa.Float(precision=5),
               existing_nullable=True)
    op.alter_column('groups', 'no_show_risk',
               existing_type=sa.NUMERIC(precision=4, scale=3),
               type_=sa.Float(precision=4),
               existing_nullable=True)
    op.alter_column('groups', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('groups', 'chat_opens_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('groups', 'chat_expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('groups', 'group_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'matching'::character varying"))
    op.alter_column('groups', 'member_limit',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('100'))
    op.alter_column('groups', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_groups_activity_id'), table_name='groups')
    op.drop_index(op.f('idx_groups_chat_expires'), table_name='groups')
    op.drop_index(op.f('idx_groups_group_type'), table_name='groups')
    op.drop_index(op.f('idx_groups_interest_tags'), table_name='groups', postgresql_using='gin')
    op.drop_index(op.f('idx_groups_status'), table_name='groups')
    op.alter_column('hosts', 'total_experiences_hosted',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('hosts', 'rating_avg',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               type_=sa.Float(precision=3),
               existing_nullable=True)
    op.alter_column('hosts', 'background_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('hosts', 'interview_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('hosts', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('hosts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('platform_config', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sos_events', 'lat',
               existing_type=sa.NUMERIC(precision=10, scale=7),
               type_=sa.Float(precision=10),
               existing_nullable=True)
    op.alter_column('sos_events', 'lng',
               existing_type=sa.NUMERIC(precision=10, scale=7),
               type_=sa.Float(precision=10),
               existing_nullable=True)
    op.alter_column('sos_events', 'emergency_contact_notified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('sos_events', 'resolved',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('sos_events', 'resolution_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'open'::character varying"))
    op.alter_column('sos_events', 'admin_notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('sos_events', 'triggered_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_sos_resolution_status'), table_name='sos_events')
    op.drop_index(op.f('idx_sos_triggered_at'), table_name='sos_events')
    op.drop_index(op.f('idx_sos_user'), table_name='sos_events')
    op.alter_column('user_blocks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_user_blocks_blocker'), table_name='user_blocks')
    op.alter_column('user_history', 'met_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_user_history_met_at'), table_name='user_history')
    op.drop_index(op.f('idx_user_history_pair'), table_name='user_history')
    op.drop_index(op.f('idx_user_history_user'), table_name='user_history')
    op.alter_column('users', 'verification_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'unverified'::character varying"))
    op.alter_column('users', 'verified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'user'::character varying"))
    op.alter_column('users', 'onboarding_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'home_lat',
               existing_type=sa.NUMERIC(precision=10, scale=7),
               type_=sa.Float(precision=10),
               existing_nullable=True)
    op.alter_column('users', 'home_lng',
               existing_type=sa.NUMERIC(precision=10, scale=7),
               type_=sa.Float(precision=10),
               existing_nullable=True)
    op.alter_column('users', 'city',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Bangalore'::character varying"))
    op.alter_column('users', 'travel_radius_km',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('15'))
    op.alter_column('users', 'live_lat',
               existing_type=sa.NUMERIC(precision=10, scale=7),
               type_=sa.Float(precision=10),
               existing_nullable=True)
    op.alter_column('users', 'live_lng',
               existing_type=sa.NUMERIC(precision=10, scale=7),
               type_=sa.Float(precision=10),
               existing_nullable=True)
    op.alter_column('users', 'last_active_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('users', 'women_only_preference',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'streak_weeks',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'total_experiences',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'total_people_met',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'total_neighborhoods_explored',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_users_active_ready'), table_name='users', postgresql_where='((onboarding_completed = true) AND (personality_vector IS NOT NULL) AND (live_lat IS NOT NULL) AND (live_lng IS NOT NULL))')
    op.drop_index(op.f('idx_users_city'), table_name='users')
    op.drop_index(op.f('idx_users_last_active'), table_name='users')
    op.drop_index(op.f('idx_users_onboarding_completed'), table_name='users')
    op.drop_index(op.f('idx_users_preferred_radius'), table_name='users')
    op.drop_index(op.f('idx_users_verification_status'), table_name='users')
    op.alter_column('venues', 'lat',
               existing_type=sa.NUMERIC(precision=10, scale=7),
               type_=sa.Float(precision=10),
               existing_nullable=True)
    op.alter_column('venues', 'lng',
               existing_type=sa.NUMERIC(precision=10, scale=7),
               type_=sa.Float(precision=10),
               existing_nullable=True)
    op.alter_column('venues', 'city',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Bangalore'::character varying"))
    op.alter_column('venues', 'wander_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('venues', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_venues_city_area'), table_name='venues')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_venues_city_area'), 'venues', ['city', 'area'], unique=False)
    op.alter_column('venues', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('venues', 'wander_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('venues', 'city',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Bangalore'::character varying"))
    op.alter_column('venues', 'lng',
               existing_type=sa.Float(precision=10),
               type_=sa.NUMERIC(precision=10, scale=7),
               existing_nullable=True)
    op.alter_column('venues', 'lat',
               existing_type=sa.Float(precision=10),
               type_=sa.NUMERIC(precision=10, scale=7),
               existing_nullable=True)
    op.create_index(op.f('idx_users_verification_status'), 'users', ['verification_status'], unique=False)
    op.create_index(op.f('idx_users_preferred_radius'), 'users', ['preferred_radius_km'], unique=False)
    op.create_index(op.f('idx_users_onboarding_completed'), 'users', ['onboarding_completed'], unique=False)
    op.create_index(op.f('idx_users_last_active'), 'users', ['last_active_at'], unique=False)
    op.create_index(op.f('idx_users_city'), 'users', ['city'], unique=False)
    op.create_index(op.f('idx_users_active_ready'), 'users', [sa.literal_column('last_active_at DESC')], unique=False, postgresql_where='((onboarding_completed = true) AND (personality_vector IS NOT NULL) AND (live_lat IS NOT NULL) AND (live_lng IS NOT NULL))')
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'total_neighborhoods_explored',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'total_people_met',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'total_experiences',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'streak_weeks',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'women_only_preference',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'last_active_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'live_lng',
               existing_type=sa.Float(precision=10),
               type_=sa.NUMERIC(precision=10, scale=7),
               existing_nullable=True)
    op.alter_column('users', 'live_lat',
               existing_type=sa.Float(precision=10),
               type_=sa.NUMERIC(precision=10, scale=7),
               existing_nullable=True)
    op.alter_column('users', 'travel_radius_km',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('15'))
    op.alter_column('users', 'city',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Bangalore'::character varying"))
    op.alter_column('users', 'home_lng',
               existing_type=sa.Float(precision=10),
               type_=sa.NUMERIC(precision=10, scale=7),
               existing_nullable=True)
    op.alter_column('users', 'home_lat',
               existing_type=sa.Float(precision=10),
               type_=sa.NUMERIC(precision=10, scale=7),
               existing_nullable=True)
    op.alter_column('users', 'onboarding_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'user'::character varying"))
    op.alter_column('users', 'verified_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'verification_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'unverified'::character varying"))
    op.create_index(op.f('idx_user_history_user'), 'user_history', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_history_pair'), 'user_history', ['user_id', 'other_user_id'], unique=False)
    op.create_index(op.f('idx_user_history_met_at'), 'user_history', ['met_at'], unique=False)
    op.alter_column('user_history', 'met_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_user_blocks_blocker'), 'user_blocks', ['blocker_id'], unique=False)
    op.alter_column('user_blocks', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_sos_user'), 'sos_events', ['user_id'], unique=False)
    op.create_index(op.f('idx_sos_triggered_at'), 'sos_events', ['triggered_at'], unique=False)
    op.create_index(op.f('idx_sos_resolution_status'), 'sos_events', ['resolution_status'], unique=False)
    op.alter_column('sos_events', 'triggered_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sos_events', 'admin_notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('sos_events', 'resolution_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'open'::character varying"))
    op.alter_column('sos_events', 'resolved',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('sos_events', 'emergency_contact_notified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('sos_events', 'lng',
               existing_type=sa.Float(precision=10),
               type_=sa.NUMERIC(precision=10, scale=7),
               existing_nullable=True)
    op.alter_column('sos_events', 'lat',
               existing_type=sa.Float(precision=10),
               type_=sa.NUMERIC(precision=10, scale=7),
               existing_nullable=True)
    op.alter_column('platform_config', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('hosts', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('hosts', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('hosts', 'interview_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('hosts', 'background_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('hosts', 'rating_avg',
               existing_type=sa.Float(precision=3),
               type_=sa.NUMERIC(precision=3, scale=2),
               existing_nullable=True)
    op.alter_column('hosts', 'total_experiences_hosted',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('idx_groups_status'), 'groups', ['status'], unique=False)
    op.create_index(op.f('idx_groups_interest_tags'), 'groups', ['interest_tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_groups_group_type'), 'groups', ['group_type'], unique=False)
    op.create_index(op.f('idx_groups_chat_expires'), 'groups', ['chat_expires_at'], unique=False)
    op.create_index(op.f('idx_groups_activity_id'), 'groups', ['activity_id'], unique=False)
    op.alter_column('groups', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('groups', 'member_limit',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('100'))
    op.alter_column('groups', 'group_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'matching'::character varying"))
    op.alter_column('groups', 'chat_expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('groups', 'chat_opens_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('groups', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('groups', 'no_show_risk',
               existing_type=sa.Float(precision=4),
               type_=sa.NUMERIC(precision=4, scale=3),
               existing_nullable=True)
    op.alter_column('groups', 'match_score',
               existing_type=sa.Float(precision=5),
               type_=sa.NUMERIC(precision=5, scale=3),
               existing_nullable=True)
    op.create_index(op.f('idx_group_members_user'), 'group_members', ['user_id'], unique=False)
    op.create_index(op.f('idx_group_members_group'), 'group_members', ['group_id'], unique=False)
    op.alter_column('group_members', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('group_members', 'sos_triggered',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('group_members', 'checked_in',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('group_members', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'member'::character varying"))
    op.create_index(op.f('idx_friend_conn_user'), 'friend_connections', ['user_id', 'status'], unique=False)
    op.create_index(op.f('idx_friend_conn_friend'), 'friend_connections', ['friend_id', 'status'], unique=False)
    op.alter_column('friend_connections', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('friend_connections', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('friend_connections', 'compatibility_score',
               existing_type=sa.Float(precision=5),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=True)
    op.alter_column('friend_connections', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.create_index(op.f('idx_flagged_users_status'), 'flagged_users', ['status'], unique=False)
    op.alter_column('flagged_users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('flagged_users', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('flagged_users', 'flag_type',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'manual'::character varying"))
    op.create_index(op.f('idx_chat_messages_group'), 'chat_messages', ['group_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_chat_messages_expires'), 'chat_messages', ['expires_at'], unique=False)
    op.alter_column('chat_messages', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_messages', 'expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('chat_messages', 'message_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'text'::character varying"))
    op.alter_column('admin_notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('admin_notifications', 'opened_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('admin_notifications', 'delivered_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('idx_activities_tags'), 'activities', ['tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_activities_status'), 'activities', ['status'], unique=False)
    op.create_index(op.f('idx_activities_scheduled_at'), 'activities', ['scheduled_at'], unique=False)
    op.create_index(op.f('idx_activities_is_local_event'), 'activities', ['is_local_event'], unique=False)
    op.create_index(op.f('idx_activities_city'), 'activities', ['city'], unique=False)
    op.create_index(op.f('idx_activities_category'), 'activities', ['category'], unique=False)
    op.create_index(op.f('idx_activities_area'), 'activities', ['area'], unique=False)
    op.alter_column('activities', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('activities', 'visibility',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'public'::character varying"))
    op.alter_column('activities', 'ticket_price_inr',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('activities', 'ticket_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'free'::character varying"))
    op.alter_column('activities', 'max_capacity',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('50'))
    op.alter_column('activities', 'min_capacity',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('4'))
    op.alter_column('activities', 'is_local_event',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('activities', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'open'::character varying"))
    op.alter_column('activities', 'phone_free_encouraged',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('activities', 'max_groups',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('3'))
    op.alter_column('activities', 'women_only',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('activities', 'group_size_max',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('8'))
    op.alter_column('activities', 'group_size_min',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('4'))
    op.alter_column('activities', 'duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('180'))
    op.alter_column('activities', 'confirmed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('activities', 'scheduled_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('activities', 'city',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Bangalore'::character varying"))
    op.alter_column('activities', 'lng',
               existing_type=sa.Float(precision=10),
               type_=sa.NUMERIC(precision=10, scale=7),
               existing_nullable=True)
    op.alter_column('activities', 'lat',
               existing_type=sa.Float(precision=10),
               type_=sa.NUMERIC(precision=10, scale=7),
               existing_nullable=True)
    op.drop_table('user_reports')
    # ### end Alembic commands ###
